plugins {
    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'java'
}

/* group = 'com.example'
version = '1.0.0'
sourceCompatibility = '21' */
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = "https://maven.pkg.github.com/AI-Solutions-App/ai-solutions-java-shared"
        credentials {
            username = System.getenv("GITHUB_ACTOR")
            password = System.getenv("GITHUB_TOKEN")
        }
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation('org.springframework.boot:spring-boot-starter-mail') {
        exclude group: 'org.eclipse.angus', module: 'jakarta.mail'
    }
    implementation "org.springframework.boot:spring-boot-starter-validation"
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation "org.springframework.boot:spring-boot-starter-test"

    compileOnly "org.projectlombok:lombok:1.18.42"
    annotationProcessor "org.projectlombok:lombok:1.18.42"

    implementation 'com.aisolutions:ai-solutions-java-shared:0.1.1'
    implementation 'com.sun.mail:jakarta.mail:2.0.1'

}

def javaExtension = project.extensions.getByType(JavaPluginExtension)

/* tasks.named('test') {
    useJUnitPlatform()
} */
tasks.named("bootRun") {
    jvmArgs = ["-Dspring.profiles.active=dev"]
}
