plugins {
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'java'
}

/* group = 'com.example'
version = '1.0.0'
sourceCompatibility = '21' */
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)  // or 21 if you need
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation "org.springframework.boot:spring-boot-starter-validation"
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation "org.springframework.boot:spring-boot-starter-test"

}

def javaExtension = project.extensions.getByType(JavaPluginExtension)

/* tasks.named('test') {
    useJUnitPlatform()
} */
tasks.named("bootRun") {
    jvmArgs = ["-Dspring.profiles.active=dev"]
}